apiVersion: batch/v1
kind: CronJob
metadata:
  name: test
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-job-02
              image: mycontainerregistry02.azurecr.io/cron-job-02:v1.1
          restartPolicy: OnFailure